import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/auth.css',
                'resources/css/admin.css',
                'resources/css/owner.css',
                'resources/css/user.css',
                'resources/css/courts.css',
                'resources/css/court-details.css',
                'resources/css/booking.css',
                'resources/css/bookings.css',
                'resources/css/wishlist.css',
                'resources/js/app.js',
                'resources/js/api.js',
                'resources/js/auth/login.js',
                'resources/js/auth/register.js',
                'resources/js/user/user-layout.js',
                'resources/js/user/dashboard.js',
                'resources/js/user/courts.js',
                'resources/js/user/court-details.js',
                'resources/js/user/booking.js',
                'resources/js/user/bookings.js',
                'resources/js/user/wishlist.js',
                'resources/js/user/tournaments.js',
                'resources/js/user/become_owner.js',
                'resources/js/user/profile.js',
                'resources/js/owner/dashboard.js',
                'resources/js/owner/courts.js',
                'resources/js/owner/time_slots.js',
                'resources/js/owner/bookings.js',
                'resources/js/owner/tournaments.js',
                'resources/js/owner/earnings.js',
                'resources/js/owner/reviews.js',
                'resources/js/owner/profile.js',
                'resources/js/admin/dashboard.js',
                'resources/js/admin/owner_applications.js',
                'resources/js/admin/courts.js',
                'resources/js/admin/users.js',
                'resources/js/admin/banners.js',
                'resources/js/admin/bookings.js',
                'resources/js/admin/payouts.js',
                'resources/js/admin/reviews.js',
                'resources/js/admin/tournaments.js',
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
    server: {
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});
